USE labsis_seg;

CREATE TABLE IF NOT EXISTS algoritmos(
	id INT NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	id_padre TEXT NULL,
    visitas INT NOT NULL DEFAULT 0,
	PRIMARY KEY (id)
)ENGINE=MyISAM DEFAULT CHARACTER SET=utf8;

ALTER TABLE articulos ADD id_algoritmo INT DEFAULT NULL;
