DROP DATABASE IF EXISTS labsis_seg;
CREATE DATABASE labsis_seg;
USE labsis_seg;

CREATE TABLE IF NOT EXISTS articulos(
	id INT NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	contenido TEXT NOT NULL,
    id_tecnica INT NOT NULL,
    fecha_hora DATETIME NOT NULL,
    activada BOOLEAN NOT NULL DEFAULT TRUE,
	PRIMARY KEY (id)
)ENGINE=MyISAM DEFAULT CHARACTER SET=utf8;

CREATE TABLE IF NOT EXISTS tecnicas(
	id INT NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
        id_padre INT NULL,
	PRIMARY KEY (id)
)ENGINE=MyISAM DEFAULT CHARACTER SET=utf8;


