DROP DATABASE IF EXISTS labsis_seg;
CREATE DATABASE labsis_seg;
USE labsis_seg;

CREATE TABLE IF NOT EXISTS articulos(
	id INT NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	contenido TEXT NOT NULL,
    id_tecnica INT NOT NULL,
    fecha_hora DATETIME NOT NULL,
    activada BOOLEAN NOT NULL DEFAULT TRUE,
	PRIMARY KEY (id)
)ENGINE=MyISAM DEFAULT CHARACTER SET=utf8;

CREATE TABLE IF NOT EXISTS historial_articulos(
	id INT NOT NULL AUTO_INCREMENT,
	id_articulo INT NOT NULL,
	diff BLOB NOT NULL,
	diff_titulo BLOB NOT NULL,
	fecha_hora DATETIME NOT NULL,
	PRIMARY KEY (id)
)ENGINE=MyISAM DEFAULT CHARACTER SET=utf8;

CREATE TABLE IF NOT EXISTS tecnicas(
	id INT NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
    id_padre INT NULL,
    technique_type_id INT,
	PRIMARY KEY (id)
)ENGINE=MyISAM DEFAULT CHARACTER SET=utf8;

CREATE TABLE IF NOT EXISTS techniques_types(
    id INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    PRIMARY KEY(id)
)ENGINE=MyISAM DEFAULT CHARACTER SET=utf8;
